[project]
name = "hackathon"
authors = []
description = ""
telemetry = true
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[[project.requirements]]
contract_id = "ST17D0SY6T9M01CQN3F5HBXCC86JBWTAT8RMFJAB1.nft-trait"

[[project.requirements]]
contract_id = "ST17D0SY6T9M01CQN3F5HBXCC86JBWTAT8RMFJAB1.vote-invitation"

[project.cache_location]
path = ".requirements"
[contracts.votr]
path = "contracts/votr.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
